spring:
  datasource:
    url: jdbc:mysql://192.168.44.157:3306/shiro?useUnicode=true&characterEncoding=UTF-8
    username:
    password:
    driver-class-name: com.mysql.jdbc.Driver

    #druid config
    initialSize: 5
    minIdle: 6
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20

  thymeleaf:
    enabled: true

#mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ulknow.frame.domain

mapper:
  mappers: com.ulknow.frame.util.MyMapper
  not-empty: false
  identity: MYSQL